SELECT
        `observations`.`id` AS `observation_id`,
        `releves`.`id` AS `session_id`,
        `espaces_verts`.`protocols`.`name` AS `protocole`,
        `sites`.`structure_id` AS `structure_id`,
        `espaces_verts`.`structures`.`name` AS `structure_nom`,
        `releves`.`user_id` AS `user_id`,
        `releves`.`observation_area_id` AS `site_id`,
        JSON_VALUE(`releves`.`data`, '$.espaceVert.nom') AS `site`,
        ST_AsText(`sites`.`geodata`) AS `site_geometry`,
        `sites`.`departement` AS `site_departement`,
        `sites`.`postcode` AS `site_zip_code`,
        JSON_VALUE(`releves`.`data`, '$.espaceVert.surface') AS `surface`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.espaceVert.objectifs')) AS `objectifs`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.objectifsAutrePrecision') AS `objectifs_autre`,
        `frequentation`.`title` AS `frequentation`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.espaceVert.occupationsSolAnterieures')) AS `occupations_sol_anterieures`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.occupationsSolAnterieuresAutrePrecision') AS `occupations_sol_anterieures_autre`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.dateCreation') AS `site_creation`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.espaceVert.travauxAnterieurs')) AS `travaux_anterieurs`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.travauxAnterieursAutrePrecision') AS `travaux_anterieurs_autre`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.espaceVert.travauxSolAnterieurs')) AS `travaux_sol_anterieurs`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.travauxSolAnterieursAutrePrecision') AS `travaux_sol_anterieurs_autre`,
        `frequence_travail_sol`.`title` AS `frequence_travail_sol`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.frequenceTravailSolAutrePrecision') AS `frequence_travail_sol_autre`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.frequenceTravailSolRegulierPrecision') AS `frequence_travail_sol_regulier`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.espaceVert.amendements')) AS `amendements`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.amendementsAutrePrecision') AS `amendements_autre`,
        `frequence_amendement`.`title` AS `frequence_amendement`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.frequenceAmendementAutrePrecision') AS `frequence_amendement_autre`,
        JSON_VALUE(`releves`.`data`,
                '$.espaceVert.frequenceAmendementRegulierPrecision') AS `frequence_amendement_regulier`,
        JSON_VALUE(`releves`.`data`, '$.date') AS `session_date`,
        JSON_VALUE(`releves`.`data`, '$.heureDebut') AS `session_starting_time`,
        JSON_VALUE(`releves`.`data`, '$.heureFin') AS `session_ending_time`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`, '$.observateurs')) AS `observateurs`,
        `hauteur_vegetation`.`title` AS `hauteur_vegetation`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`, '$.milieux')) AS `milieux`,
        JSON_VALUE(`releves`.`data`,
                '$.milieuxAutrePrecision') AS `milieux_autre`,
        `semis_sursemis`.`title` AS `semis_sursemis`,
        `fauche`.`title` AS `fauche`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`, '$.periodesFauches')) AS `periodes_fauches`,
        `frequence_fauches`.`title` AS `frequence_fauches`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`, '$.paturages')) AS `paturages`,
        JSON_VALUE(`releves`.`data`,
                '$.paturagesAutrePrecision') AS `paturages_autre`,
        JSON_VALUE(`releves`.`data`, '$.pressionPaturage') AS `pression_paturage`,
        JSON_VALUE(`releves`.`data`,
                '$.dureeAnnuellePaturage') AS `duree_annuelle_paturage`,
        `exportation_residus`.`title` AS `exportation_residus`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`,
                        '$.traitementsPhytosanitaires')) AS `traitements_phyto`,
        JSON_VALUE(`releves`.`data`,
                '$.traitementsPhytosanitairesAutrePrecision') AS `traitements_phyto_autre`,
        JSON_UNQUOTE(JSON_EXTRACT(`releves`.`data`, '$.pressions')) AS `pressions`,
        JSON_VALUE(`releves`.`data`,
                '$.pressionsAutrePrecision') AS `pressions_autre`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_UNQUOTE(JSON_VALUE(`releves`.`data`, '$.commentaire')),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `commentaire`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[0].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q1`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[1].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q2`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[2].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q3`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[3].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q4`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[4].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q5`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[5].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q6`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[6].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q7`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[7].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q8`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[8].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q9`,
        JSON_VALUE(`releves`.`data`,
                '$.tigesLigneuses[9].nombreTigesLigneuses') AS `tiges_ligneuses_nombre_Q10`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.taxon') AS `taxon`,
        JSON_VALUE(`taxon_latin`.`data`,
                '$.nomScientifique') AS `taxon_nom_scientifique`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.cdNomTaxref') AS `cd_nom`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ1') AS `taxon_count_Q1`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ2') AS `taxon_count_Q2`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ3') AS `taxon_count_Q3`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ4') AS `taxon_count_Q4`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ5') AS `taxon_count_Q5`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ6') AS `taxon_count_Q6`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ7') AS `taxon_count_Q7`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ8') AS `taxon_count_Q8`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ9') AS `taxon_count_Q9`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.occurenceQ10') AS `taxon_count_Q10`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.presenceHorsQuadrat') AS `taxon_count_hors_quadrat`,
        JSON_VALUE(`espaces_verts`.`observations`.`data`,
                '$.listeFlorilege') AS `taxon_liste_florilege`,
        `releves`.`created_at` AS `date_creation_bdd`,
        `releves`.`updated_at` AS `date_modification_bdd`
    FROM
        ((((((((((((((`espaces_verts`.`participations` `releves`
        LEFT JOIN `espaces_verts`.`observation_areas` `sites` ON (`sites`.`id` = `releves`.`observation_area_id`))
        LEFT JOIN `espaces_verts`.`users` ON (`espaces_verts`.`users`.`id` = `releves`.`user_id`))
        LEFT JOIN `espaces_verts`.`structures` ON (`espaces_verts`.`structures`.`id` = `sites`.`structure_id`))
        LEFT JOIN `espaces_verts`.`protocols` ON (`espaces_verts`.`protocols`.`id` = `releves`.`protocol_id`))
        LEFT JOIN `espaces_verts`.`observations` ON (`espaces_verts`.`observations`.`participation_id` = `releves`.`id`))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `frequentation` ON (`frequentation`.`value` = JSON_VALUE(`releves`.`data`, '$.espaceVert.frequentation')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `frequence_travail_sol` ON (`frequence_travail_sol`.`value` = JSON_VALUE(`releves`.`data`, '$.espaceVert.frequenceTravailSol')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `frequence_amendement` ON (`frequence_amendement`.`value` = JSON_VALUE(`releves`.`data`, '$.espaceVert.frequenceAmendement')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `hauteur_vegetation` ON (`hauteur_vegetation`.`value` = JSON_VALUE(`releves`.`data`, '$.hauteurVegetation')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `semis_sursemis` ON (`semis_sursemis`.`value` = JSON_VALUE(`releves`.`data`, '$.semisSursemis')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `fauche` ON (`fauche`.`value` = JSON_VALUE(`releves`.`data`, '$.fauche')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `frequence_fauches` ON (`frequence_fauches`.`value` = JSON_VALUE(`releves`.`data`, '$.frequenceFauches')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `exportation_residus` ON (`exportation_residus`.`value` = JSON_VALUE(`releves`.`data`, '$.exportationResidus')))
        LEFT JOIN `espaces_verts`.`thesaurus_values` `taxon_latin` ON (`taxon_latin`.`title` = JSON_VALUE(`espaces_verts`.`observations`.`data`, '$.taxon')))
    WHERE
        `releves`.`protocol_id` = 1
            AND `sites`.`deleted_at` IS NULL
            AND `releves`.`deleted_at` IS NULL
            AND `espaces_verts`.`observations`.`deleted_at` IS NULL
    ORDER BY `releves`.`id` DESC , JSON_VALUE(`espaces_verts`.`observations`.`data`,
            '$.taxon')